services:
  myfeedbackhub.api:
    image: ${DOCKER_REGISTRY-}myfeedbackhubapi
    container_name: myfeedbackhub-api
    build:
      context: .
      dockerfile: src/MyFeedbackHub.Api/Dockerfile
    environment:
        - ASPNETCORE_URLS=http://+:4002;https://+:4003;http://+:4005
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - 4002:4002
        - 4003:4003
        - 4005:4005
    restart: always 
    networks:
        - myfeedbackhub-network
  
  myfeedbackhub.postgresql.server:
    container_name: myfeedbackhub.postgresql.server
    image: postgres:latest
    environment:
      - POSTGRES_DB=myfeedbackhub
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=YourStrong!Password123
    volumes:
      - ./infra/postgresql/temp_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myfeedbackhub-network

  myfeedbackhub.redis.cache:
    container_name: myfeedbackhub.redis.cache
    image: redis:latest
    restart: always
    ports:
        - "6379:6379"
    networks:
        - myfeedbackhub-network

  myfeedbackhub.rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ messaging port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - myfeedbackhub-network

  myfeedbackhub.background.services:
    container_name: myfeedbackhub-background-services
    build:
      context: .
      dockerfile: src/MyFeedbackHub.BackgroundServices/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
    depends_on:
      - myfeedbackhub.rabbitmq
    restart: always
    networks:
      - myfeedbackhub-network

networks:
  myfeedbackhub-network:
    name: myfeedbackhub-network
    driver: bridge